services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greeka_todo
    ports:
      - '55432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      PORT: 3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greeka_todo
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:


